version: 2
jobs:
  build:
    parallelism: 2
    environment:
      _JAVA_OPTIONS: "-Xmx1g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      # why is this required when i dont have a container yet??
      # I will be pushing the container once it is built
      # if CCI is downloading the code then it should run the build commands
      # from within that process
      - image: rwideman/gs-spring-boot-docker:latest
    steps:
      - checkout
      - run:
          name: Run tests in parallel
          command: |
            # build jar
            ./gradlew build && java -jar build/libs/gs-spring-boot-docker-0.1.0.jar
            # build container
            docker build --build-arg DEPENDENCY=build/dependency -t rwideman/gs-spring-boot-docker .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build