version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8u242-jdk
    steps:
      - checkout
      - setup_remote_docker:
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          ./gradlew jib --image=rwideman/gs-spring-boot-docker:$TAG
