version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk-alpine # build container
    working_directory: ~/gs-spring-boot-docker
    steps:
      - checkout
      - run:
          name: Install gradle and docker
          command: |
            apk update
            apk add gradle docker
      - run:
          name: Build jar
          command: |
            ./gradlew build && java -jar build/libs/gs-spring-boot-docker-0.1.0.jar
      - run:
          name: Build container
          command: |
            docker build --build-arg DEPENDENCY=build/dependency -t rwideman/gs-spring-boot-docker .
      - run:
          name: Build and tag
          command: |
            ./gradlew jib --image=rwideman/gs-spring-boot-docker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build